### ISSUE TITLE
Add OWFS (1wire) support

### ISSUE THREAD

**Issue by iganin67** [stas-demydiuk/domoticz-docker#1]
Hi Stas,
Would be possible to add 1wire support to the docker?
I have tested your container and really happy how it works.
However, i'm missing 1wire support.
I was able to launched the following command in the terminal of the container:

apt install owfs
apt install nano
Change the  /etc/owfs.conf (i can do it manually afterwards) 
mkdir /mnt/1wire 
Change  /etc/fuse.conf (allow….i can do it manually afterwards)
owfs -C -uall -m /mnt/1wire —allow_other

Once it's done i could add 1wire hardware to Domoticz.
Unfortunately, once the container is rebooted, I lost data.

Last but not least, can you add the link via  the domoticz folders "script" and "plugins" to the host via volume as datа from those folders can be lost during the updates.

Thank you a lot in advance/ Дякую наперед
Kind Regards,
Ihor Hanin/

**Comment by stas-demydiuk** [comment]
Closing the issue as image is no longer maintained
