### ISSUE TITLE
Setting timezone

### ISSUE THREAD

**Issue by superjunky** [stas-demydiuk/domoticz-docker#10]
Hi,

I am having trouble to getting Domoticz to reflect the correct timezone.

There seems to be no /etc/timezone folder.. Does this image require to install tzdata?

Can you offer some advice? thanks!

**Comment by stas-demydiuk** [comment]
What platform do you use to run the image (arm or x64)?

**Comment by superjunky** [comment]
Thanks for replying!

x86_64

**Comment by Freekers** [comment]
If you want to use the same timezone as the Docker host, you can use the following volume mount:

```
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
```

**Comment by superjunky** [comment]
That's what I did, but it didn't give me the correct time. Running Docker on a Synology, I guess it's related to user-permissions.
I got the correct time only after installing the tzdata package like this:
```
ln -fs /usr/share/zoneinfo/Europe/Amsterdam /etc/localtime
export DEBIAN_FRONTEND=noninteractive
apt-get install -y tzdata
dpkg-reconfigure --frontend noninteractive tzdata
```
Perhaps the image needs this by default? I'm no Docker-wizard, so no clue if others go this route. I usually don't have timezone issues with other images.

**Comment by Freekers** [comment]
Hmm, that's strange, because using that volume mount works fine for me on my Synology DS918+. 
However, I do run the container as root, but that shouldn't really make a difference, as /etc/localtime is world readable:

```
-rw-r--r-- 1 root root 2.9K May 14  2020 /etc/localtime
```

**Comment by stas-demydiuk** [comment]
Closing the issue as image is no longer maintained
