### ISSUE TITLE
Feature request: Add Python3 plugins "requests" and "paramiko"

### ISSUE THREAD

**Issue by MiloshCZ** [stas-demydiuk/domoticz-docker#11]
Hi,
I would like to use https://github.com/d-EScape/Domoticz_iDetect plugin, but Python3 plugins "requests" and "paramiko" are missing.

Is it possible to add this modules?

Thank you

**Comment by stas-demydiuk** [comment]
Since plugins folder is part of volume try to install dependencies directly to plugin's folder by doing the following:
```
docker exec -it <your_domoticz_container_name> sh
apt-get -y install python3-pip
cd plugins/<plugin_name>
pip3 install <your_python_module_name> -t .
```

**Comment by MiloshCZ** [comment]
Thank you for your support. Everything is OK.
