### ISSUE TITLE
dynamically add plugins and backup directory on host storage

### ISSUE THREAD

**Issue by zandhaas** [stas-demydiuk/domoticz-docker#14]
I have a question about this container.

I want to be able to add plugings that are not already available in your image.
Do I need to add an extra volume mapping to the plugin directory to accomplish this?
And I also want the Domoticz database backups on host storage. This also is possible by adding an extra volume mapping to the domoticz backup directory?

**Comment by Freekers** [comment]
Both are possible. Use the following volume mounts to do so

```
    volumes:
     - "./backups:/opt/domoticz/backups"
     - "./plugins:/opt/domoticz/plugins"
```

Don't forget to 'Enable Automatic Backup' in the Settings

**Comment by stas-demydiuk** [comment]
Closing the issue as image is no longer maintained
