### ISSUE TITLE
Error: GLIBC_2.28 not found

### ISSUE THREAD

**Issue by bikeymouse** [stas-demydiuk/domoticz-docker#2]
Hi, 
Thanks for your work. I tried this image on an Raspberry PI 2B+ but It won't start. 
I have this error in the log:
/opt/domoticz/domoticz: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.28' not found (required by /opt/domoticz/domoticz)

As I understand from the Domoticz forum this is because Domoticz  2020.1+ is build for Debian Buster which does contain GLIB 2.28 as opposed to Ubuntu.

**Comment by stas-demydiuk** [comment]
Should now be ok starting from `demydiuk/domoticz:4.11952-beta-arm32v7`

**Comment by bikeymouse** [comment]
Hi, thanks. 
Unfortunately 4.11952 is an older beta, currently Domoticz has released 2020.1.
Or do you mean that building with your Dockerfile should also work for 2020.1?

**Comment by stas-demydiuk** [comment]
I guess you've missed something, it the latest available beta from Apr 20

**Comment by bikeymouse** [comment]
Well may be I missed this alternative naming scheme of calling this release **4**.11952 , because as far as I know the latest release and beta's are called **2020**.1.11953 at the Domoticz site: https://www.domoticz.com/downloads/

**Comment by stas-demydiuk** [comment]
Updated naming as well
