### ISSUE TITLE
How to activate SSL support?

### ISSUE THREAD

**Issue by bikeymouse** [stas-demydiuk/domoticz-docker#3]
Hi, first of all, thanks for this great docker-file for Domoticz. 

I got everything working fine, except I do not get SSL support working.

At startup Domoticz says the service is running:
`
2020-05-01 11:56:35.101 Status: WebServer(HTTP) started on address: 0.0.0.0 with port 8080
2020-05-01 11:56:35.126 Status: WebServer(SSL) started on address: 0.0.0.0 with port 443
`

I mapped port 443 of the container to the host port 443 but get no response. 

Even inside the container, using curl "localhost:443" I get an "Empty reply from the server"  response, however with netstat I can see that domotiz is actually listening on port 443.

Do you have any idea what I'm missing here?

**Comment by stas-demydiuk** [comment]
Container passes `-www 8080` argument to Domoticz by default. To activate ssl I guess you need to additionally pass `-sslwww 443` argument

**Comment by bikeymouse** [comment]
Yeah, I thought so too and tried that, but that made no difference. 

But the fact that Domoticz says in the log that it started the SSL webserver on port 443 suggests that it is running by default.

**Comment by boscorelly** [comment]
use a nginx rewrite proxy container :)

**Comment by stas-demydiuk** [comment]
Just checked and a combination of
```
  ports:
    - 8443:8443
  command: -www 8080 -sslwww 8443
```
works just fine. Added the information into readme
