### ISSUE TITLE
Python 3.6 or 3.7 ?

### ISSUE THREAD

**Issue by rezzalex** [stas-demydiuk/domoticz-docker#4]
Hello,

thanks for your Container

i tried to use this Python domoticz plugin : https://github.com/dnpwwo/Domoticz-Google-Plugin
is it clearly noticed that python 3.6x can be a problem for this plugin.

I installed it and i have this error message in domoticz Logs : 

`` Error: (GoogleDevs) failed to load 'plugin.py', Python Path used was '/opt/domoticz/plugins/Domoticz-Google-Plugin/:/usr/lib/python37.zip:/usr/lib/python3.7:/usr/lib/python3.7/lib-dynload:/usr/local/lib/python3.7/dist-packages:/usr/lib/python3/dist-packages:/usr/lib/python3.7/dist-packages'.
2020-05-13 19:00:08.059 Error: (GoogleCast) Module Import failed, exception: 'ModuleNotFoundError'
2020-05-13 19:00:08.059 Error: (GoogleCast) Module Import failed: ' Name: pychromecast'
2020-05-13 19:00:08.059 Error: (GoogleCast) Error Line details not available.``

![image](https://user-images.githubusercontent.com/35136439/81842766-de6d9c80-954c-11ea-9492-070594465d9b.png)

and Domoticz indicate
![image](https://user-images.githubusercontent.com/35136439/81842798-edece580-954c-11ea-8317-ae558ea6073d.png)

Can you help me ?

**Comment by stas-demydiuk** [comment]
As I understand from the log plugin just can't find `pychromecast` dependency, probably you need to install it

**Comment by rezzalex** [comment]
pychromecast is installed

**Comment by stas-demydiuk** [comment]
Are you sure that it is installed in container not in your host system?

**Comment by rezzalex** [comment]
Sure but in python 3.6 :
![IMG_20200514_214539](https://user-images.githubusercontent.com/35136439/81978859-67a7d080-962c-11ea-9d3a-6290b88900c1.jpg)

**Comment by rezzalex** [comment]
Could you update your container do that the defaut python version.is 3.7.5 ?

**Comment by rezzalex** [comment]
I don't remeber having this problem with my previous "outisde docker" version of Domoticz... any idea ?

**Comment by dnpwwo** [comment]
Did you install pychromecast using 'sudo'?

That normally fixes this kind of thing in a non-container world

**Comment by rezzalex** [comment]
Logged as root when connected in SSH to container and sudo command unknowned in your container...

**Comment by rezzalex** [comment]
I have followed these steps to upgrade to python 3,7 and now all Work.
https://dev.to/serhatteker/how-to-upgrade-to-python-3-7-on-ubuntu-18-04-18-10-5hab
I just did not understand How Domoticz could indicate working with Python 3.7.5 previously...
