### ISSUE TITLE
plugins and themes ?

### ISSUE THREAD

**Issue by boscorelly** [stas-demydiuk/domoticz-docker#5]
Hi,

with your image, is it possible to use plugins and themes in domoticz ?

**Comment by stas-demydiuk** [comment]
Yes, sure, you just need to create volumes for these folders and store your plugins and themes inside them.

**Comment by boscorelly** [comment]
volumes:
      - /datastore/domoticz/themes:/config/themes ?

**Comment by stas-demydiuk** [comment]
```
volumes:
- /datastore/domoticz/themes:/opt/domoticz/www/styles
```
