### ISSUE TITLE
Migration Docker Image Issue

### ISSUE THREAD

**Issue by rezzalex** [stas-demydiuk/domoticz-docker#6]
Hello, thanks for your docker images.
I tried to move from a beta version to another one, but despite having binded everything concerning configuration, DZ is "empty" after the launch. Here is my BIND config : 
![image](https://user-images.githubusercontent.com/35136439/86584096-b0bd3680-bf84-11ea-8308-a59c61f9325b.png)

When SSH into the docker, I can see that volumes are correctly binded with the host and that my DB File has almost the same size and the same date of lasst modification as th one I "saved" in the host, and manually somewhere else....

**INSIDE DZ : CONTAINER**
![image](https://user-images.githubusercontent.com/35136439/86584281-f11cb480-bf84-11ea-884e-c4988ae5b980.png)

**INSIDE My HOST :** 
![image](https://user-images.githubusercontent.com/35136439/86584442-2fb26f00-bf85-11ea-86d4-9c47676fa239.png)

**DB manually saved somewhere else :**
![image](https://user-images.githubusercontent.com/35136439/86584294-fa0d8600-bf84-11ea-873f-4dd36217450f.png)

So My Question is :  Where the hell DZ store his DB in your container ?
I could restore the DB with the DZ web GUI but want to understand first the container thing...

Thanks you very much

**Comment by stas-demydiuk** [comment]
Domoticz stores database in `/config`, so your volume should work fine.
One additional note: domoticz doesn't update file with the database in realtime, so you need to stop service to have the file updated with the latest changes.

**Comment by rezzalex** [comment]
Ok.

So with the next beta release, I will test this procedure :

1. Replace the docker  image.
2. Start the container.
3. STOP the container
4. Start it again.

Is that correct ?

Thanks

**Comment by rezzalex** [comment]
Can you also confirm that binding the /script repository is useless because everything is inside the Database ?

**Comment by stas-demydiuk** [comment]
As I know - yes, Domiticz stores all scripts in the database.
