### ISSUE TITLE
Running plugin Domoticz-deCONZ: missing python lib requests

### ISSUE THREAD

**Issue by senmr** [stas-demydiuk/domoticz-docker#7]
Hi,

I want to use the Smanar/Domoticz-deCONZ plugin in my domoticz setup.
I created the docker with:
`docker create --name=domoticz  -p 8081:8080 -v \<path-to-config\>:/config -v \<path to plugins\>:/opt/domoticz/plugins --restart unless-stopped demydiuk/domoticz:latest`
I installed the Domoticz-deCONZ plug in in \<path to plugins\>

I see the plugin in the list of hardwares and can create a hardware instance.

The plugin seems to be loaded OK but it complains about:
```
2020-07-30 10:34:11.584  Error: (zigbee) Your pyton version miss requests library,
2020-07-30 10:34:11.584  Error: (zigbee) To install it, type : sudo -H pip3 install requests | sudo -H pip install requests
```

Any idea how to fix this?

**Comment by stas-demydiuk** [comment]
You need to install requests dependency. My suggestion is to install it directly in the plugin's folder. See response in #11
