### ISSUE TITLE
import docker file in portainer fails

### ISSUE THREAD

**Issue by knireis** [stas-demydiuk/domoticz-docker#9]
I imported the Dockerfile.x86-64 in portainer on my qnap ts453D.
However it fails with:
COPY failed: stat /share/CACHEDEV1_DATA/Container/container-station-data/lib/docker/tmp/docker-builder284893746/domoticz: no such file or directory

I usually work with prebuild docker images, but i need to add a package to the image so i thought to make one myself. I have not much experience with docker so i don't know where to  look to solve this.

**Comment by stas-demydiuk** [comment]
I guess that's because you don't have added hooks (or your setup does not support them). See `hooks` folder to check what commands are required prior to start building the image
